# Generated by Django 4.2.1 on 2023-05-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectDetection', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='textDetection',
        ),
    ]
