# Generated by Django 4.2.1 on 2023-05-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objectDetection', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='textDetection',
            new_name='BCaptcha',
        ),
    ]
